version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - echo "Zipping Lambda function"
      - cd backend
      - zip -r lambda.zip lambda_function.py

artifacts:
  files:
    - lambda.zip
